
spring:
  application.name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productsdb
management:
  endpoints.web.exposure.include: health,info
server:
  port: 8082